(import joy :prefix "")
(import ./routes :as routes)
(import ./layout :as layout)


(def app (-> (handler routes/app)
             (db (env :db-name))
             (layout layout/app)
             (logger)
             (csrf-token)
             (session)
             (extra-methods)
             (query-string)
             (body-parser)
             (server-error)
             (not-found)
             (x-headers)
             (static-files)))
